// src/server.rs — gRPC service implementation

use rust_decimal::Decimal;
use rust_decimal_macros::dec;
use std::str::FromStr;
use tonic::{Request, Response, Status};
use tracing::{debug, warn};

use crate::curve::{CurveConfig, CurveKind};

// Generated by tonic from proto/curve.proto
pub mod proto {
    tonic::include_proto!("curve");
}

use proto::{
    curve_engine_server::CurveEngine,
    CurveType, MarketCapRequest, MarketCapResponse,
    PriceCurveRequest, PriceCurveResponse, PricePoint,
    SpotPriceRequest, SpotPriceResponse,
    TradeRequest, TradeResponse,
};

pub struct CurveEngineService;

// ── Helpers ──────────────────────────────────────────────────────────────────

fn parse_dec(s: &str, field: &str) -> Result<Decimal, Status> {
    Decimal::from_str(s)
        .map_err(|_| Status::invalid_argument(format!("invalid decimal for {field}: '{s}'")))
}

fn build_config(params: Option<proto::CurveParams>) -> Result<CurveConfig, Status> {
    let p = params.ok_or_else(|| Status::invalid_argument("params required"))?;

    let curve_type = match CurveType::try_from(p.curve_type).unwrap_or(CurveType::Quadratic) {
        CurveType::Linear      => CurveKind::Linear,
        CurveType::Quadratic   => CurveKind::Quadratic,
        CurveType::Exponential => CurveKind::Exponential,
    };

    // Default slope values if not provided (or "")
    let slope_str = if p.slope.is_empty() {
        match curve_type {
            CurveKind::Linear      => "0.0000001".to_string(),
            CurveKind::Quadratic   => "0.000000001".to_string(),
            CurveKind::Exponential => "0.0002".to_string(),
        }
    } else {
        p.slope.clone()
    };

    let total_supply_str = if p.total_supply.is_empty() {
        "20000".to_string()
    } else {
        p.total_supply.clone()
    };

    Ok(CurveConfig {
        curve_type,
        init_price:   parse_dec(&p.init_price,    "init_price")?,
        slope:        parse_dec(&slope_str,         "slope")?,
        total_supply: parse_dec(&total_supply_str, "total_supply")?,
    })
}

// ── gRPC handler implementations ─────────────────────────────────────────────

#[tonic::async_trait]
impl CurveEngine for CurveEngineService {

    async fn get_spot_price(
        &self,
        req: Request<SpotPriceRequest>,
    ) -> Result<Response<SpotPriceResponse>, Status> {
        let r       = req.into_inner();
        let cfg     = build_config(r.params)?;
        let supply  = parse_dec(&r.current_supply, "current_supply")?;

        let price      = cfg.spot_price(supply).map_err(|e| Status::internal(e.to_string()))?;
        let market_cap = cfg.market_cap(supply).map_err(|e| Status::internal(e.to_string()))?;

        debug!(%price, %supply, "spot_price");

        Ok(Response::new(SpotPriceResponse {
            price:      price.to_string(),
            market_cap: market_cap.to_string(),
        }))
    }

    async fn get_buy_cost(
        &self,
        req: Request<TradeRequest>,
    ) -> Result<Response<TradeResponse>, Status> {
        let r      = req.into_inner();
        let cfg    = build_config(r.params)?;
        let supply = parse_dec(&r.current_supply, "current_supply")?;
        let amount = parse_dec(&r.amount, "amount")?;

        let result = cfg.buy_cost(supply, amount)
            .map_err(|e| Status::invalid_argument(e.to_string()))?;

        debug!(eth=%result.eth_amount, %amount, "buy_cost");

        Ok(Response::new(TradeResponse {
            eth_amount:      result.eth_amount.to_string(),
            price_per_token: result.price_per_token.to_string(),
            new_supply:      result.new_supply.to_string(),
            new_spot_price:  result.new_spot_price.to_string(),
            would_graduate:  result.would_graduate,
        }))
    }

    async fn get_sell_return(
        &self,
        req: Request<TradeRequest>,
    ) -> Result<Response<TradeResponse>, Status> {
        let r      = req.into_inner();
        let cfg    = build_config(r.params)?;
        let supply = parse_dec(&r.current_supply, "current_supply")?;
        let amount = parse_dec(&r.amount, "amount")?;

        let result = cfg.sell_return(supply, amount)
            .map_err(|e| Status::invalid_argument(e.to_string()))?;

        debug!(eth=%result.eth_amount, %amount, "sell_return");

        Ok(Response::new(TradeResponse {
            eth_amount:      result.eth_amount.to_string(),
            price_per_token: result.price_per_token.to_string(),
            new_supply:      result.new_supply.to_string(),
            new_spot_price:  result.new_spot_price.to_string(),
            would_graduate:  false,
        }))
    }

    async fn get_market_cap(
        &self,
        req: Request<MarketCapRequest>,
    ) -> Result<Response<MarketCapResponse>, Status> {
        let r      = req.into_inner();
        let cfg    = build_config(r.params)?;
        let supply = parse_dec(&r.supply, "supply")?;

        let market_cap  = cfg.market_cap(supply).map_err(|e| Status::internal(e.to_string()))?;
        let spot_price  = cfg.spot_price(supply).map_err(|e| Status::internal(e.to_string()))?;
        let progress    = cfg.progress_pct(supply)
            .to_f64()
            .unwrap_or(0.0);

        Ok(Response::new(MarketCapResponse {
            market_cap:   market_cap.to_string(),
            spot_price:   spot_price.to_string(),
            progress_pct: progress,
        }))
    }

    async fn get_price_curve(
        &self,
        req: Request<PriceCurveRequest>,
    ) -> Result<Response<PriceCurveResponse>, Status> {
        let r      = req.into_inner();
        let cfg    = build_config(r.params)?;
        let points = (r.points as usize).min(1000).max(2);

        let step = cfg.total_supply / Decimal::from(points as u64);
        let mut result = Vec::with_capacity(points);

        for i in 0..=points {
            let supply = step * Decimal::from(i as u64);
            match cfg.spot_price(supply) {
                Ok(price) => result.push(PricePoint {
                    supply: supply.to_string(),
                    price:  price.to_string(),
                }),
                Err(e) => warn!("price_curve point {i} error: {e}"),
            }
        }

        Ok(Response::new(PriceCurveResponse { points: result }))
    }
}

use rust_decimal::prelude::ToPrimitive;
